// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team2509.robot.subsystems;

import org.usfirst.frc.team2509.robot.RobotMap;

import edu.wpi.first.wpilibj.command.Subsystem;

import com.ctre.CANTalon;


/**
 *
 */
public class Climb extends Subsystem {
    private final CANTalon MOTOR1 = RobotMap.CLIMB_MOTOR;
    private final CANTalon MOTOR2 = RobotMap.CLIMB_ALT;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
    }
    public CANTalon getMotor1(){
    	return MOTOR1;
    }
    public CANTalon getMotor2(){
    	return MOTOR2;
    }
}

